view_enabled=true;
view_visible[0]=true;
layers=
[
layer_get_id("Assets_1"),
layer_get_id("Assets_2"),
layer_get_id("Assets_3"),
]
layerpos=
[
layer_get_x(layers[0]),
layer_get_x(layers[1]),
layer_get_x(layers[2]),
];
layerpos[0]=
[
layer_get_y(layers[0]),
layer_get_y(layers[1]),
layer_get_y(layers[2]),
];
